"""v1 analysis output schema — the versioned contract the LLM's structured
output is constrained to (CLAUDE.md Rule 3: a schema change that could
alter a real analysis output is a new version file, never an in-place
edit of v1 once a real run has used it).

Maps directly onto the Brain's 5 steps
(claude/buffett-munger-rebuild-sprint-plan-2026-09-21.md):

  1. Business Quality & Moat        -> MoatAssessment
  2. Financial Fortress             -> `capital_efficiency` + `financial_fortress`
  3. Macro & Industry Stress Test   -> `macro_stress_test`
  4. Valuation & Margin of Safety   -> `valuation_synthesis` (the DCF/multiples
     numbers themselves are Sprint 3's deterministic output, already computed
     before the LLM ever sees them — this section is the model's narrative
     synthesis of numbers it was handed, not new math: CLAUDE.md Rule 1)
  5. Verdict                        -> VerdictContent

Every section carries `evidence_ids`: the packet IDs (app/services/analysis/
evidence_packet.py) that section's claims are grounded in — CLAUDE.md
Rule 2. `app/services/analysis/{blind_pass,reconciliation_pass}.py` checks
every cited ID actually exists in the packet handed to that call; an
unknown ID is a citation warning, not a silently accepted claim.

Every field here is *content the model produces*, not a number the
pipeline could compute cheaper/more reliably itself: it never asks the
model to reproduce a ROIC figure, a DCF value, or a price target — those
are already deterministic facts inside the evidence packet, and the
verdict's price-target range is set from the Sprint 3 DCF bear/bull
scenarios in Python (see app/services/analysis/pipeline.py), never
generated by the LLM.
"""
from __future__ import annotations

from typing import Literal

from pydantic import BaseModel

MoatRating = Literal["Wide", "Narrow", "None"]
VerdictRating = Literal["Strong Buy", "Buy", "Hold", "Sell", "Avoid"]
MoatSource = Literal[
    "brand",
    "pricing_power",
    "switching_costs",
    "network_effects",
    "cost_advantage",
    "intellectual_property",
    "distribution",
]

# Same values as the MoatSource Literal above, as a plain tuple for
# non-typing uses (e.g. prompt rendering, assumptions).
MOAT_SOURCES: tuple[str, ...] = (
    "brand",
    "pricing_power",
    "switching_costs",
    "network_effects",
    "cost_advantage",
    "intellectual_property",
    "distribution",
)


class MoatSourceRating(BaseModel):
    source: MoatSource
    rating: MoatRating
    reasoning: str
    evidence_ids: list[str]


class MoatAssessment(BaseModel):
    circle_of_competence_summary: str
    overall_rating: MoatRating
    sources: list[MoatSourceRating]
    evidence_ids: list[str]


class NarrativeAssessment(BaseModel):
    """A qualitative synthesis section: `financial_fortress` (Brain Step 2's
    balance-sheet/earnings-quality read), `macro_stress_test` (Step 3), and
    `capital_efficiency`/`valuation_synthesis` (Steps 1.3/4's narrative
    over already-computed numbers) all share this shape."""

    summary: str
    evidence_ids: list[str]


class VerdictContent(BaseModel):
    rating: VerdictRating
    thesis_bullets: list[str]
    top_risks: list[str]
    metrics_to_monitor: list[str]
    invalidation_triggers: list[str]
    evidence_ids: list[str]


class BlindPassOutputV1(BaseModel):
    """What the blind pass (no user notes — CLAUDE.md Rule 4) produces."""

    moat: MoatAssessment
    capital_efficiency: NarrativeAssessment
    financial_fortress: NarrativeAssessment
    macro_stress_test: NarrativeAssessment
    valuation_synthesis: NarrativeAssessment
    verdict: VerdictContent


class ReconciliationOutputV1(BaseModel):
    """What the reconciliation pass produces: the blind pass's verdict,
    reconsidered in light of the holding's notes (if any) — always still
    evidence-grounded, never a bare deference to the notes."""

    verdict: VerdictContent
    reconciliation_narrative: str
    changed_from_blind: bool
    evidence_ids: list[str]


def cited_evidence_ids_blind(output: BlindPassOutputV1) -> set[str]:
    """Every evidence_id cited anywhere in a blind-pass output."""
    ids: set[str] = set(output.moat.evidence_ids)
    for source in output.moat.sources:
        ids.update(source.evidence_ids)
    ids.update(output.capital_efficiency.evidence_ids)
    ids.update(output.financial_fortress.evidence_ids)
    ids.update(output.macro_stress_test.evidence_ids)
    ids.update(output.valuation_synthesis.evidence_ids)
    ids.update(output.verdict.evidence_ids)
    return ids


def cited_evidence_ids_reconciliation(output: ReconciliationOutputV1) -> set[str]:
    return set(output.evidence_ids) | set(output.verdict.evidence_ids)
